### ISSUE TITLE
Add Amazon Bedrock provider

### ISSUE THREAD

**Issue by samuelrince** [genai-impact/ecologits#26]
## Description

Add [Amazon Bedrock](https://aws.amazon.com/bedrock/) provider.

## Solution

Amazon Bedrock uses its on API and Python package.

Python package: [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html)

Amazon Bedrock: 

- [User Guide](https://docs.aws.amazon.com/bedrock/latest/userguide/what-is-bedrock.html) 
- [API Reference](https://docs.aws.amazon.com/bedrock/latest/APIReference/welcome.html) 
- [List of models](https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids.html)

Code example:

```python
import boto3
import json
brt = boto3.client(service_name='bedrock-runtime')

body = json.dumps({
    "prompt": "\n\nHuman: explain black holes to 8th graders\n\nAssistant:",
    "max_tokens_to_sample": 300,
    "temperature": 0.1,
    "top_p": 0.9,
})

modelId = 'anthropic.claude-v2'
accept = 'application/json'
contentType = 'application/json'

response = brt.invoke_model(body=body, modelId=modelId, accept=accept, contentType=contentType)

response_body = json.loads(response.get('body').read())

# text
print(response_body.get('completion'))
```

**Comment by celeriev** [comment]
Hi @samuelrince, I'm upping this again. Maybe it could be re-opened? As many orgs mine is mainly relying on AWS Bedrock
