### ISSUE TITLE
Configuration system

### ISSUE THREAD

**Issue by samuelrince** [genai-impact/ecologits#57]
## Description

Enable the user to configure EcoLogits library. An example is changing the impact factors of the electricity mix to match datacenter country.

## Solution

Make available some options in the `init` method of `EcoLogits` object. 

## Considerations

Start simple.

**Comment by adrienbanse** [comment]
Let's also implement a `verbose` initialisation parameter such as suggested in https://github.com/genai-impact/ecologits/issues/65
