### ISSUE TITLE
Implement warnings

### ISSUE THREAD

**Issue by samuelrince** [genai-impact/ecologits#59]
## Description

Display warnings in the `impacts` section of each response when needed. These warnings can inform the user on the quality of the estimation for closed-source models, for instance.

## Solution

Some warnings are already defined in the models.csv file.

**Comment by adrienbanse** [comment]
@samuelrince As an attribute of `Impacts`? We could also simply use `logger.warning`, or both

**Comment by samuelrince** [comment]
As an attribute of `Impacts`, because logging it would also be very spammy. I'd like to finish the new structure of model repository before adding the feature though ;)

**Comment by adrienbanse** [comment]
@samuelrince This is closed right?
