### ISSUE TITLE
Bug -- Initialisation Google Instrument because of other Google dependencies

### ISSUE THREAD

**Issue by cvarrei** [genai-impact/ecologits#62]
By using another implementation of Ecologits than Google's in my project, because one of my dependencies from another library is ‘google-auth’, my environment contains a ‘google’ module but without the generative-ai aspect. It tries to initialise the Google instrumentor, but (rightly) fails. I did a few tests, using the specific generative Google module (google-generativeai) modifying this :

```
def init_google_instrumentor() -> None:
    if importlib.util.find_spec("google") is not None:
        from ecologits.tracers.google_tracer import GoogleInstrumentor
```

to:

```
def init_google_instrumentor() -> None:
    if importlib.util.find_spec("google-generativeai") is not None:
        from ecologits.tracers.google_tracer import GoogleInstrumentor
```

This fixes the bug, but it may need to be tested to ensure that it doesn't affect the correct functioning of the Google tracer.

**Comment by adrienbanse** [comment]
Thanks @cvarrei!
